version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
